// <auto-generated />
using System;
using JslInspection.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JslInspection.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212193841_AddEmailOutbox")]
    partial class AddEmailOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JslInspection.Api.Models.ChecklistItemTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("DropdownOptionsCsv")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ItemText")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("RequiresPhotoIfNotOk")
                        .HasColumnType("bit");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId", "SeqNo");

                    b.ToTable("ChecklistItemTemplates");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            ChecklistTemplateId = 1,
                            InputType = "PassFail",
                            IsRequired = true,
                            ItemText = "Any oil leakage observed?",
                            RequiresPhotoIfNotOk = true,
                            SeqNo = 1
                        },
                        new
                        {
                            Id = 102,
                            ChecklistTemplateId = 1,
                            DropdownOptionsCsv = "Good,Average,Poor",
                            InputType = "Dropdown",
                            IsRequired = true,
                            ItemText = "Housekeeping condition",
                            RequiresPhotoIfNotOk = false,
                            SeqNo = 2
                        },
                        new
                        {
                            Id = 103,
                            ChecklistTemplateId = 1,
                            InputType = "Number",
                            IsRequired = true,
                            ItemText = "Motor temperature (°C)",
                            MaxValue = 90m,
                            MinValue = 0m,
                            RequiresPhotoIfNotOk = false,
                            SeqNo = 3
                        },
                        new
                        {
                            Id = 104,
                            ChecklistTemplateId = 1,
                            InputType = "Text",
                            IsRequired = false,
                            ItemText = "Remarks (if any)",
                            RequiresPhotoIfNotOk = false,
                            SeqNo = 4
                        },
                        new
                        {
                            Id = 201,
                            ChecklistTemplateId = 2,
                            InputType = "PassFail",
                            IsRequired = true,
                            ItemText = "Belt alignment OK?",
                            RequiresPhotoIfNotOk = true,
                            SeqNo = 1
                        },
                        new
                        {
                            Id = 202,
                            ChecklistTemplateId = 2,
                            InputType = "PassFail",
                            IsRequired = true,
                            ItemText = "Abnormal noise/vibration?",
                            RequiresPhotoIfNotOk = true,
                            SeqNo = 2
                        },
                        new
                        {
                            Id = 203,
                            ChecklistTemplateId = 2,
                            InputType = "PassFail",
                            IsRequired = true,
                            ItemText = "Any damaged idlers/rollers visible?",
                            RequiresPhotoIfNotOk = true,
                            SeqNo = 3
                        },
                        new
                        {
                            Id = 204,
                            ChecklistTemplateId = 2,
                            InputType = "Text",
                            IsRequired = false,
                            ItemText = "General comments",
                            RequiresPhotoIfNotOk = false,
                            SeqNo = 4
                        });
                });

            modelBuilder.Entity("JslInspection.Api.Models.ChecklistSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("OverallRemark")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId");

                    b.ToTable("ChecklistSubmissions");
                });

            modelBuilder.Entity("JslInspection.Api.Models.ChecklistSubmissionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistItemTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("ChecklistSubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsNotOk")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ValueNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ValueText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistSubmissionId", "ChecklistItemTemplateId");

                    b.ToTable("ChecklistSubmissionItems");
                });

            modelBuilder.Entity("JslInspection.Api.Models.ChecklistTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Daily visual & basic parameter checks for CRM area.",
                            IsActive = true,
                            Name = "CRM Daily Inspection"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Weekly detailed checklist for conveyor health.",
                            IsActive = true,
                            Name = "CRM Conveyor Weekly Check"
                        });
                });

            modelBuilder.Entity("JslInspection.Api.Models.EmailOutbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ChecklistSubmissionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("EmailOutbox");
                });

            modelBuilder.Entity("JslInspection.Api.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EquipmentTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Plant", "Area", "EquipmentTag")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("JslInspection.Api.Models.SubmissionPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ChecklistSubmissionItemId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistSubmissionItemId");

                    b.ToTable("SubmissionPhotos");
                });

            modelBuilder.Entity("JslInspection.Api.Models.ChecklistItemTemplate", b =>
                {
                    b.HasOne("JslInspection.Api.Models.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistTemplate");
                });

            modelBuilder.Entity("JslInspection.Api.Models.ChecklistSubmission", b =>
                {
                    b.HasOne("JslInspection.Api.Models.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany()
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChecklistTemplate");
                });

            modelBuilder.Entity("JslInspection.Api.Models.ChecklistSubmissionItem", b =>
                {
                    b.HasOne("JslInspection.Api.Models.ChecklistSubmission", "ChecklistSubmission")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistSubmission");
                });

            modelBuilder.Entity("JslInspection.Api.Models.ChecklistSubmission", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JslInspection.Api.Models.ChecklistTemplate", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
